version: "3.9"

services:
  renford-api:
    container_name: "renford-api"
    build:
      context: ./renford-api
      dockerfile: Dockerfile
    env_file:
      - ./renford-api/.env
    restart: always
    networks:
      - network
    volumes:
      - uploads:/uploads
    dns:
      - 8.8.8.8
      - 8.8.4.4

  renford-nginx:
    container_name: "renford-nginx"
    build: ./nginx
    volumes:
      - uploads:/uploads
    restart: always
    depends_on:
      - renford-api
    networks:
      - network
    labels:
      - traefik.enable=true
      - traefik.docker.network=network
      - traefik.http.routers.renford-nginx.rule=Host(`api.renford.store`)
      - traefik.http.routers.renford-nginx.entrypoints=websecure
      - traefik.http.routers.renford-nginx.tls.certresolver=letsencryptresolver
      - traefik.http.services.renford-nginx.loadbalancer.server.port=80

  renford-prisma:
    container_name: "renford-prisma"
    build:
      context: ./renford-api/prisma
      dockerfile: Dockerfile
    env_file:
      - ./renford-api/.env
    restart: always
    networks:
      - network
    labels:
      - traefik.enable=true
      - traefik.docker.network=network
      - traefik.http.routers.renford-prisma.rule=Host(`prisma.renford.store`)
      - traefik.http.routers.renford-prisma.entrypoints=websecure
      - traefik.http.routers.renford-prisma.tls.certresolver=letsencryptresolver
      - traefik.http.services.renford-prisma.loadbalancer.server.port=5000

  renford-dashboard:
    container_name: "renford-dashboard"
    build:
      context: ./renford-dashboard
      dockerfile: Dockerfile
    env_file:
      - ./renford-dashboard/.env
    restart: always
    networks:
      - network
    labels:
      - traefik.enable=true
      - traefik.docker.network=network
      - traefik.http.routers.renford-dashboard.rule=Host(`renford.store`)
      - traefik.http.routers.renford-dashboard.entrypoints=websecure
      - traefik.http.routers.renford-dashboard.tls.certresolver=letsencryptresolver
      - traefik.http.services.renford-dashboard.loadbalancer.server.port=80

networks:
  network:
    external:
      name: "saas_network"

volumes:
  uploads:
